\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{Leafcutter}
\LoadClass[titlepage]{report}

\newif\if@doctor
\newif\if@coadvisor
\newif\if@thaithesis
\@coadvisorfalse

% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
% Option declaration
\DeclareOption{doctor} {
    \@doctortrue
} \DeclareOption{master} {
    \@doctorfalse
} \DeclareOption{coadvisor} {
    \@coadvisortrue
} \DeclareOption{thaithesis} {
    \@thaithesistrue
} \DeclareOption{engthesis} {
    \@engthesistrue
}

